# These are supported funding model platforms

github: [brollikk, emanuallan] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: cryptohomeless # Replace with a single Patreon username
custom: ['https://cryptoforthehomeless.org', 'https://cryptohomeless.home.blog', 'http://www.cpmma.net', 'https://theadamsbrand.com', 'https://www.papercash.com' ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
