# These are supported funding model platforms
patreon: cryptohomeless # Replace with a single Patreon username
custom: ['https://cryptoforthehomeless.org', 'https://cryptohomeless.home.blog', 'http://www.cpmma.net', 'https://theadamsbrand.com', 'https://www.papercash.com' ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
